import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <Link href="/" className="inline-flex font-bold hover:underline py-3 pl-0 pr-2">
              Home
            </Link>
            <Link href="/notes" className="inline-flex font-bold hover:underline py-3 px-2">
              Notes
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
